### ISSUE TITLE
大神，这个主题超帅，有个问题啊，我这是怎么回事

### ISSUE THREAD

**Issue by JadenFK** [ShanaMaid/hexo-theme-shana#38]
执行hexo generate时出现了下面的问题
ERROR E:\MyBlog\themes\ShanaMaid\layout\page.ejs:1
 >> 1| <%- partial('_partial/article', {post: page, index: false}) %>

E:\MyBlog\themes\ShanaMaid\layout\_partial\article.ejs:36
    34|         <a href="<%- post.permalink %>#disqus_thread" class="article-comment-link"><%= __('comment') %></a>
    35|       <% } %>
 >> 36|       <%- partial('post/tag') %>
    37|     </footer>
    38|   </div>
    39|   <% if (!index){ %>

E:\MyBlog\themes\ShanaMaid\layout\_partial\post\tag.ejs:2
    1| <% if (post.tags && post.tags.length){ %>
 >> 2|   <%- list_tags(post.tags, {
    3|     show_count: false,
    4|     class: 'article-tag'
    5|   }) %>

tags.sort is not a function
TypeError: E:\MyBlog\themes\ShanaMaid\layout\page.ejs:1
 >> 1| <%- partial('_partial/article', {post: page, index: false}) %>

E:\MyBlog\themes\ShanaMaid\layout\_partial\article.ejs:36
    34|         <a href="<%- post.permalink %>#disqus_thread" class="article-comment-link"><%= __('comment') %></a>
    35|       <% } %>
 >> 36|       <%- partial('post/tag') %>
    37|     </footer>
    38|   </div>
    39|   <% if (!index){ %>

E:\MyBlog\themes\ShanaMaid\layout\_partial\post\tag.ejs:2
    1| <% if (post.tags && post.tags.length){ %>
 >> 2|   <%- list_tags(post.tags, {
    3|     show_count: false,
    4|     class: 'article-tag'
    5|   }) %>

tags.sort is not a function
    at Object.listTagsHelper (E:\MyBlog\node_modules\hexo\lib\plugins\helper\list_tags.js:24:15)
    at eval (eval at compile (E:\MyBlog\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:12:17)
    at returnedFn (E:\MyBlog\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (E:\MyBlog\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (E:\MyBlog\node_modules\hexo\lib\theme\view.js:49:23)
    at Object.partial (E:\MyBlog\node_modules\hexo\lib\plugins\helper\partial.js:38:15)
    at eval (eval at compile (E:\MyBlog\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:88:17)
    at returnedFn (E:\MyBlog\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (E:\MyBlog\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (E:\MyBlog\node_modules\hexo\lib\theme\view.js:49:23)
    at Object.partial (E:\MyBlog\node_modules\hexo\lib\plugins\helper\partial.js:38:15)
    at eval (eval at compile (E:\MyBlog\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:9:17)
    at returnedFn (E:\MyBlog\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (E:\MyBlog\node_modules\hexo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (E:\MyBlog\node_modules\hexo\lib\theme\view.js:30:15)
    at route.set (E:\MyBlog\node_modules\hexo\lib\hexo\index.js:394:29)
    at tryCatcher (E:\MyBlog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\MyBlog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\MyBlog\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:452:10)
    at resume_ (_stream_readable.js:899:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by ShanaMaid** [comment]
tags标签被你删了吧？
